// <auto-generated />
namespace Agency.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateReservationadvance_reservation_percentage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateReservationadvance_reservation_percentage));
        
        string IMigrationMetadata.Id
        {
            get { return "202111171914420_updateReservationadvance_reservation_percentage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
