// <auto-generated />
namespace Agency.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_hotel_benefit_model_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_hotel_benefit_model_name));
        
        string IMigrationMetadata.Id
        {
            get { return "202111031836222_change_hotel_benefit_model_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
