// <auto-generated />
namespace Agency.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_is_refunf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_is_refunf));
        
        string IMigrationMetadata.Id
        {
            get { return "202201180845116_add_is_refunf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
